case_study:
  outputs:
    dev:
      dataset: dbt_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: erudite-flag-384915
      threads: 1
      type: bigquery
  target: dev

